Remove userProfileExtended feature flag
ClouDesire/java-api-client pull request #594
Opened 2020-12-28 08:23 UTC by malteo

ClouDesire/support/issues/4290

2021-01-11 15:53 UTC, gionn submitted a review, later dismissed

2021-01-12 13:15 UTC, gionn requested changes

2021-01-12 13:15 UTC, gionn commented on cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/MyUserDTO.java
> -    private IdentificationDocumentDTO document;
rm IdentificationDocumentDTO

2021-01-12 13:17 UTC, pimuzzo submitted a review, later dismissed

2021-01-12 15:09 UTC, gionn submitted a review, later dismissed

2021-01-21 14:56 UTC, gionn approved these changes

2021-01-21 14:56 UTC, merged