Expose previous billing period end date in order
ClouDesire/java-api-client pull request #781
Opened 2022-02-11 15:08 UTC by malteo

### TODO

- [ ] Release new client version

2022-02-14 16:38 UTC, manuelmazzuola requested changes

2022-02-14 16:38 UTC, manuelmazzuola commented on cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/BaseSubscriptionDTO.java
> +    @ApiModelProperty( hidden = true )
qui non si può lasciare anche value?

2022-02-14 16:40 UTC, malteo commented on cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/BaseSubscriptionDTO.java
> +    @ApiModelProperty( hidden = true )
tanto è nascosto, non lo stamperebbe da nessuna parte

2022-02-15 08:14 UTC, manuelmazzuola approved these changes

2022-02-15 09:01 UTC, pimuzzo submitted a review, later dismissed

2022-02-15 09:12 UTC, manuelmazzuola requested changes

2022-02-15 09:12 UTC, manuelmazzuola commented on cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/BaseSubscriptionDTO.java
> +     * @deprecated by {@link #getBillingPeriodEnd()}
![image](https://user-images.githubusercontent.com/1757492/154029876-9fbf67f9-dcf3-47d4-9502-b45184b77312.png)

2022-02-15 09:12 UTC, manuelmazzuola commented on cloudesire-api-client-dto/src/main/java/com/cloudesire/platform/apiclient/dto/model/dto/BaseSubscriptionDTO.java
> +     * @deprecated by {@link #getBillingPeriodEnd()}
se non vuoi farlo leva la regola da sonar

2022-02-15 09:34 UTC, manuelmazzuola approved these changes

2022-02-15 10:16 UTC, merged